export const mockTrainers = [
  {
    id: "trainer-1",
    name: "Mike Johnson",
    email: "mike@fitplanhub.com",
    avatar: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=150&h=150&fit=crop&crop=face",
    bio: "Certified personal trainer with 10+ years of experience in strength training and HIIT.",
    specialties: ["Strength Training", "HIIT", "Weight Loss"],
    followers: 1250,
  },
  {
    id: "trainer-2",
    name: "Sarah Williams",
    email: "sarah@fitplanhub.com",
    avatar: "https://images.unsplash.com/photo-1594381898411-846e7d193883?w=150&h=150&fit=crop&crop=face",
    bio: "Yoga and wellness expert focused on mind-body connection and flexibility.",
    specialties: ["Yoga", "Flexibility", "Meditation"],
    followers: 890,
  },
  {
    id: "trainer-3",
    name: "James Rodriguez",
    email: "james@fitplanhub.com",
    avatar: "https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=150&h=150&fit=crop&crop=face",
    bio: "Former athlete specializing in functional fitness and sports performance.",
    specialties: ["Functional Fitness", "Sports Performance", "Cardio"],
    followers: 2100,
  },
];

export const mockPlans = [
  {
    id: "plan-1",
    title: "30-Day Strength Builder",
    description: "Transform your body with this comprehensive strength training program. Includes progressive overload techniques, proper form guidance, and nutrition tips.",
    price: 49.99,
    duration: 30,
    trainerId: "trainer-1",
    trainerName: "Mike Johnson",
    category: "Strength",
    difficulty: "Intermediate",
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=250&fit=crop",
    exercises: [
      "Day 1: Chest & Triceps",
      "Day 2: Back & Biceps",
      "Day 3: Legs & Core",
      "Day 4: Rest",
      "Day 5: Full Body HIIT",
    ],
  },
  {
    id: "plan-2",
    title: "Yoga Flow Mastery",
    description: "Find your inner peace while building flexibility and strength. Perfect for beginners and intermediate practitioners looking to deepen their practice.",
    price: 29.99,
    duration: 21,
    trainerId: "trainer-2",
    trainerName: "Sarah Williams",
    category: "Yoga",
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=250&fit=crop",
    exercises: [
      "Morning Sun Salutations",
      "Vinyasa Flow Basics",
      "Deep Stretch Sessions",
      "Balance & Core Work",
      "Meditation & Breathwork",
    ],
  },
  {
    id: "plan-3",
    title: "HIIT Fat Burner Pro",
    description: "High-intensity interval training designed to maximize calorie burn and boost metabolism. Quick, effective workouts for busy professionals.",
    price: 39.99,
    duration: 14,
    trainerId: "trainer-1",
    trainerName: "Mike Johnson",
    category: "HIIT",
    difficulty: "Advanced",
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&h=250&fit=crop",
    exercises: [
      "Tabata Circuits",
      "Burpee Challenges",
      "Sprint Intervals",
      "Plyometric Training",
      "Core Finishers",
    ],
  },
  {
    id: "plan-4",
    title: "Athletic Performance",
    description: "Train like an athlete with sport-specific exercises. Improve speed, agility, power, and overall athletic performance.",
    price: 59.99,
    duration: 45,
    trainerId: "trainer-3",
    trainerName: "James Rodriguez",
    category: "Sports",
    difficulty: "Advanced",
    image: "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=400&h=250&fit=crop",
    exercises: [
      "Agility Drills",
      "Power Development",
      "Speed Training",
      "Sport-Specific Conditioning",
      "Recovery Protocols",
    ],
  },
  {
    id: "plan-5",
    title: "Beginner's Full Body",
    description: "Start your fitness journey the right way. Learn proper form, build foundational strength, and develop healthy habits.",
    price: 19.99,
    duration: 28,
    trainerId: "trainer-3",
    trainerName: "James Rodriguez",
    category: "Beginner",
    difficulty: "Beginner",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=250&fit=crop",
    exercises: [
      "Basic Movement Patterns",
      "Bodyweight Exercises",
      "Light Resistance Training",
      "Cardio Introduction",
      "Flexibility Basics",
    ],
  },
];

export const mockUsers = {
  user: {
    id: "user-1",
    email: "user@test.com",
    password: "password123",
    name: "John Doe",
    role: "user",
  },
  trainer: {
    id: "trainer-1",
    email: "trainer@test.com",
    password: "password123",
    name: "Mike Johnson",
    role: "trainer",
  },
};
